### ISSUE TITLE
Bare URLs

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-word-count#5]
Testing shows that a bare URL in a Markdown file will be included in the count. For example, the URL in the `LICENSE.md` file is:
```
http://creativecommons.org/licenses/by-sa/4.0/
```
It will be counted a 5 words:
"http", "creativecommonsorg", "licenses", "bysa",  and "4decimal0"

**Comment by jag3773** [comment]
Because our word counts are primarily for translation purposes, URLs should be excluded from the word counts.  Please make a note of this in the README when it's accomplished.

**Comment by mandolyte** [comment]
Completed and noted in README.
