### ISSUE TITLE
Filtering on expected file types

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/uw-word-count#9]
Many repos (especially those owned by user `unfoldingWord` have expected file types. One of three:
USFM, UTN/TSV, Markdown (for most others).

At present, all files are counted:
- hidden git files/folders
- YAML
- etc.

Only the expected file types should be processed.

**Comment by jag3773** [comment]
Agreed.  If it's a Scripture repo then *only* count `.usfm` files.  If it's a tN repo, then _only_ count `.tsv` files.  Otherwise, count all `.md` files.

**Comment by mandolyte** [comment]
Fleshing this out:
- if repo ends with "_tn", then only count "tsv" files.
- if repo ends with one of the following: "_ult", "_ust", "_ugnt", or "_uhb" ,then only count "usfm" files.
otherwise, only count "md" files.

**Comment by mandolyte** [comment]
@jag3773 This will logic will pick up README.md and LICENSE.md in `https://git.door43.org/unfoldingWord/en_tq`.

But perhaps, they need to be translated too!

**Comment by mandolyte** [comment]
I decided to make it so that if the URL points to a single file, it will be counted no matter what. If it has one of the three special formats, it will be counted accordingly. Otherwise, it will be counted as a long string with no special handling.
